config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  post 'webhooks' => 'webhooks#create'

  if AuthProvider.active.providable_type == DatabaseProvider.name
    devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions',
                                     confirmations: 'confirmations', passwords: 'passwords'}
  else
    devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions',
                                     confirmations: 'confirmations', passwords: 'passwords',
                                     :omniauth_callbacks => 'users/omniauth_callbacks'}
  end

  constraints :user_agent => /facebookexternalhit\/[0-9]|Twitterbot|Pinterest|Google.*snippet/ do
    root :to => 'social_bot#share', as: :bot_root
  end

  root 'application#index'

  namespace :api, as: nil, defaults: { format: :json } do
    resources :projects, only: [:index, :show, :create, :update, :destroy] do
      collection do
        get :last_published
        get :search
        get :allowed_extensions
      end
    end
    resources :openlab_projects, only: :index
    resources :machines
    resources :components
    resources :themes
    resources :licences
    resources :admins, only: [:index, :create, :destroy]
    resources :settings, only: [:show, :update, :index], param: :name
    resources :users, only: [:index, :create]
    resources :members, only: [:index, :show, :create, :update, :destroy] do
      get '/export_subscriptions', action: 'export_subscriptions', on: :collection
      get '/export_reservations', action: 'export_reservations', on: :collection
      get '/export_members', action: 'export_members', on: :collection
      put ':id/merge', action: 'merge', on: :collection
      post 'list', action: 'list', on: :collection
      get 'search/:query', action: 'search', on: :collection
      get 'mapping', action: 'mapping', on: :collection
    end
    resources :reservations, only: [:show, :create, :index, :update]
    resources :notifications, only: [:index, :show, :update] do
      match :update_all, path: '/', via: [:put, :patch], on: :collection
      get 'polling', action: 'polling', on: :collection
      get 'last_unread', action: 'last_unread', on: :collection
    end
    resources :wallet, only: [] do
      get '/by_user/:user_id', action: 'by_user', on: :collection
      get :transactions, on: :member
      put :credit, on: :member
    end

    get '/last_subscribed/:last' => "members#last_subscribed"
    get '/feeds/twitter_timelines' => "feeds#twitter_timelines"

    get 'pricing' => 'pricing#index'
    put 'pricing' => 'pricing#update'

    resources :prices, only: [:index, :update] do
      post 'compute', on: :collection
    end
    resources :coupons
    post 'coupons/validate' => 'coupons#validate'
    post 'coupons/send' => 'coupons#send_to'

    resources :trainings_pricings, only: [:index, :update]

    resources :availabilities do
      get 'machines/:machine_id', action: 'machine', on: :collection
      get 'trainings/:training_id', action: 'trainings', on: :collection
      get 'spaces/:space_id', action: 'spaces', on: :collection
      get 'reservations', on: :member
      get 'public', on: :collection
      get '/export_index', action: 'export_availabilities', on: :collection
      put ':id/lock', action: 'lock', on: :collection
    end

    resources :groups, only: [:index, :create, :update, :destroy]
    resources :subscriptions, only: [:show, :create, :update]
    resources :plans, only: [:index, :create, :update, :destroy, :show]
    resources :slots, only: [:update] do
      put 'cancel', on: :member
    end

    resources :events do
      get 'upcoming/:limit', action: 'upcoming', on: :collection
    end

    resources :invoices, only: [:index, :show, :create] do
      get 'download', action: 'download', on: :member
      post 'list', action: 'list', on: :collection
    end

    resources :trainings do
      get :availabilities, on: :member
    end
    resources :credits
    resources :categories
    resources :event_themes
    resources :age_ranges
    resources :statistics, only: [:index]
    resources :custom_assets, only: [:show, :create, :update]
    resources :tags
    resources :stylesheets, only: [:show]
    resources :auth_providers do
      get 'mapping_fields', on: :collection
      get 'active', action: 'active', on: :collection
      post 'send_code', action: 'send_code', on: :collection
    end
    resources :abuses, only: [:create]
    resources :open_api_clients, only: [:index, :create, :update, :destroy] do
      patch :reset_token, on: :member
    end
    resources :price_categories
    resources :spaces

    get 'translations/:locale/:state' => 'translations#show', :constraints => { :state => /[^\/]+/ } # allow dots in URL for 'state'

    get 'exports/:id/download' => 'exports#download'
    post 'exports/status' => 'exports#status'

    get 'version' => 'version#show'
  end

  namespace :rss, as: nil, defaults: { format: :xml } do
    resources :projects, only: [:index], as: 'rss_projects'
    resources :events, only: [:index], as: 'rss_events'
  end

  namespace :open_api do
    namespace :v1 do
      scope only: :index do
        resources :users
        resources :trainings
        resources :user_trainings
        resources :reservations
        resources :machines
        resources :bookable_machines
        resources :invoices do
          get :download, on: :member
        end
        resources :events
        resources :availabilities
      end
    end
  end

  %w(account event machine project subscription training user space).each do |path|
    post "/stats/#{path}/_search", to: "api/statistics##{path}"
    post "/stats/#{path}/export", to: "api/statistics#export_#{path}"
  end
  post '/stats/global/export', to: "api/statistics#export_global"
  post '_search/scroll', to: "api/statistics#scroll"

  match '/project_collaborator/:valid_token', to: 'api/projects#collaborator_valid', via: :get

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  apipie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  after_action :set_csrf_cookie
  cache_sweeper :stylesheet_sweeper

  respond_to :html, :json

  before_action :configure_permitted_parameters, if: :devise_controller?

  # Globally rescue Authorization Errors in controller.
  # Returning 403 Forbidden if permission is denied
  rescue_from Pundit::NotAuthorizedError, with: :permission_denied

  def index
  end

  protected
  def set_csrf_cookie
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  def verified_request?
    super || valid_authenticity_token?(session, request.headers['X-XSRF-TOKEN'])
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) <<
      {profile_attributes: [:phone, :last_name, :first_name,
        :gender, :birthday, :interest, :software_mastered,
        organization_attributes: [:name, address_attributes: [:address]]]}
    devise_parameter_sanitizer.for(:sign_up).concat [:username, :is_allow_contact, :is_allow_newsletter, :cgu, :group_id]
  end

  def default_url_options
    { :host => Rails.application.secrets.default_host, protocol: Rails.application.secrets.default_protocol }
  end

  def permission_denied
    head 403
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	include Twitter::Autolink
	require 'message_format'

	## machine/spaces availabilities are divided in multiple slots of 60 minutes
	SLOT_DURATION ||= 60

	##
	# Verify if the provided attribute is in the provided attributes array, whatever it exists or not
	# @param attributes {Array|nil}
	# @param attribute {String}
	##
	def attribute_requested?(attributes, attribute)
		attributes.try(:include?, attribute)
	end

	def bootstrap_class_for flash_type
		{ flash: 'alert-success', alert: 'alert-danger', notice: 'alert-info' }[flash_type.to_sym] || flash_type.to_s
	end

	def flash_messages(opts = {})
		flash.each do |msg_type, message|
			concat(content_tag(:div, message, class: "flash-message alert #{bootstrap_class_for(msg_type)} fade in") do
							 concat content_tag(:button, 'x', class: 'close', data: { dismiss: 'alert' })
							 concat message
						 end)
		end
		nil
	end

	def print_slot(starting, ending)
		"#{starting.strftime('%H:%M')} - #{ending.strftime('%H:%M')}"
	end

	def class_exists?(class_name)
		klass = Module.const_get(class_name)
		return klass.is_a?(Class)
	rescue NameError
		return false
	end

	##
	# Allow to treat a rails i18n key as a MessageFormat interpolated pattern. Used in ruby views (API/mails)
	# @param key {String} Ruby-on-Rails I18n key (from config/locales/xx.yml)
	# @param interpolations {Hash} list of variables to interpolate, following ICU MessageFormat syntax
	##
	def _t(key, interpolations)
		message = MessageFormat.new(I18n.t(scope_key_by_partial(key)), I18n.locale.to_s)
		text = message.format(interpolations)
		if html_safe_translation_key?(key)
			text.html_safe
		else
			text
		end
	end

	def bool_to_sym(bool)
		if (bool) then return :true else return :false end
	end

	def amount_to_f(amount)
	  amount / 100.00
	end

  ##
  # Retrieve an item in the given array of items
  # by default, the "id" is expected to match the given parameter but
  # this can be overridden by passing a third parameter to specify the
  # property to match
  ##
	def get_item(array, id, key = nil)
		array.each do |i|
			if key.nil?
				return i if i.id == id
			else
				return i if i[key] == id
			end
		end
		nil
	end

	##
	# Apply a correction for a future DateTime due to change in Daylight Saving Time (DST) period
	# @param reference {ActiveSupport::TimeWithZone}
	# @param datetime {DateTime}
	# Inspired by https://stackoverflow.com/a/12065605
	##
	def dst_correction(reference, datetime)
		res = datetime.in_time_zone(reference.time_zone.tzinfo.name)
		res = res - 1.hour if res.dst? && !reference.dst?
		res = res + 1.hour if reference.dst? && !res.dst?
		res
	end


	private
	## inspired by gems/actionview-4.2.5/lib/action_view/helpers/translation_helper.rb
	def scope_key_by_partial(key)
		if key.to_s.first == "."
			if @virtual_path
				@virtual_path.gsub(%r{/_?}, ".") + key.to_s
			else
				raise "Cannot use t(#{key.inspect}) shortcut because path is not available"
			end
		else
			key
		end
	end

	def html_safe_translation_key?(key)
		key.to_s =~ /(\b|_|\.)html$/
	end
end

app/views/application/index.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>" ng-app="application" class="app">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title><%=Setting.find_by(name: 'fablab_name').value%></title>

  <% if ENV['DEFAULT_HOST'] == 'fablab.lacasemate.fr' %>
    <script type="text/javascript" src="//use.typekit.net/rih5zfr.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <% else %>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700,800,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700,300italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Loved+by+the+King' rel='stylesheet' type='text/css'>
  <% end %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <script type="text/javascript">
      Stripe.setPublishableKey('<%= Rails.application.secrets.stripe_publishable_key %>');

      var Fablab = Fablab || {};

      Fablab.withoutPlans = ('<%= Rails.application.secrets.fablab_without_plans %>' == 'true');
      Fablab.withoutSpaces = ('<%= Rails.application.secrets.fablab_without_spaces %>' != 'false');
      Fablab.disqusShortname = "<%= Rails.application.secrets.disqus_shortname %>";
      Fablab.defaultHost = "<%= Rails.application.secrets.default_host %>";
      Fablab.gaId = "<%= Rails.application.secrets.google_analytics_id %>";

      // i18n stuff
      Fablab.locale = "<%= Rails.application.secrets.app_locale %>";
      Fablab.moment_locale = "<%= Rails.application.secrets.moment_locale %>";
      Fablab.summernote_locale = "<%= Rails.application.secrets.summernote_locale %>";
      Fablab.fullcalendar_locale = "<%= Rails.application.secrets.fullcalendar_locale %>";
      Fablab.timezone = "<%= Time.zone.tzinfo.name %>";
      Fablab.translations = {
        app: {
          shared: {
            buttons: <%= I18n.t('app.shared.buttons').to_json.html_safe %>,
            messages: <%= I18n.t('app.shared.messages').to_json.html_safe %>
          }
        }
      };
      Fablab.weekStartingDay = <%= Date.parse(Rails.application.secrets.week_starting_day).strftime('%w') %>;
      Fablab.d3DateFormat = "<%= Rails.application.secrets.d3_date_format %>";
      Fablab.uibDateFormat = "<%= Rails.application.secrets.uib_date_format %>";
      Fablab.openlabProjectsActive = <%= Rails.application.secrets.openlab_app_secret.present? %>;
      <% if Rails.application.secrets.openlab_app_id.present? %>
      Fablab.openlabAppId = "<%= Rails.application.secrets.openlab_app_id %>";
      <% else %>
      Fablab.openlabAppId = null;
      <% end %>
  </script>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_link_tag 'app.printer', media: 'print' %>
  <% if !Stylesheet.first.nil? %>
    <link rel="stylesheet" media="all" href="<%= stylesheet_path(Stylesheet.first.id) %>-<%=Stylesheet.first.updated_at.to_i.to_s%>.css" />
  <% end %>
  <base href="/"></base>

  <% if CustomAsset.get_url('favicon-file') %>
    <link rel="shortcut icon" type="image/x-icon" href="<%= CustomAsset.get_url('favicon-file') %>">
    <link rel="shortcut icon" type="image/ico" href="<%= CustomAsset.get_url('favicon-file') %>">
  <% end %>

  <!-- RSS -->
  <link rel="alternate" type="application/rss+xml" title="RSS: <%= t('app.public.projects_list.the_fablab_projects') %>" href="<%= rss_projects_path %>.xml">
  <link rel="alternate" type="application/rss+xml" title="RSS: <%= t('app.public.events_list.the_fablab_s_events') %>" href="<%= rss_events_path %>.xml">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body ng-controller="ApplicationController" ng-init="setCurrentUser(<%= current_user ? current_user.to_json : 'null' %>)" ng-cloak>
  <div growl></div>

  <%= flash_messages %>

  <section class="vbox">

    <header class="header header-md navbar navbar-fixed-top-xs">
      <div ui-view="header"></div>
    </header>

    <section ui-view="content">
      <section class="hbox stretch">
        <aside id="nav" class="aside-md bg-red hidden-print" ui-view="leftnav"></aside>

        <section id="content">
          <section class="vbox">
            <section id="content-main" class="scrollable" ui-view="main">
            </section>
          </section>
        </section>


      </section> <!-- /.hbox -->
    </section>

  </section> <!-- /.vbox -->

  <div class="app-generator">
    <span class="app-version" ng-if="currentUser && currentUser.role == 'admin'" uib-tooltip="{{'version' | translate}} {{version.version}}">
      <i class="fa fa-question-circle" aria-label="Version ?"></i>
    </span>
    <span class="text-sm">Powered by <a href="http://www.fab-manager.com" target="_blank">Fab Manager</a></span>
  </div>

<%= javascript_include_tag 'application' %>

<!-- i18n of external libraries -->
<script type="text/javascript" src="<%= asset_path "angular-i18n/angular-locale_#{Rails.application.secrets.angular_locale}.js" %>"></script>
<script type="text/javascript" src="<%= asset_path "messageformat/locale/#{Rails.application.secrets.messageformat_locale}.js" %>"></script>

<!-- if required locale does not exist, use the default "en" -->
<% if Rails.application.assets.find_asset "moment/locale/#{Rails.application.secrets.moment_locale}.js" %>
  <script type="text/javascript" src="<%= asset_path "moment/locale/#{Rails.application.secrets.moment_locale}.js" %>"></script>
<%
  elsif Rails.application.secrets.moment_locale != 'en'
    raise LoadError, "moment/locale/#{Rails.application.secrets.moment_locale}.js does not exists"
  end
%>
<!-- if required locale does not exist, use the default "en-US" -->
<% if Rails.application.assets.find_asset "summernote/lang/summernote-#{Rails.application.secrets.summernote_locale}.js" %>
  <script type="text/javascript" src="<%= asset_path "summernote/lang/summernote-#{Rails.application.secrets.summernote_locale}.js" %>"></script>
<%
  elsif Rails.application.secrets.summernote_locale != 'en-US'
    raise LoadError, "summernote/lang/summernote-#{Rails.application.secrets.summernote_locale}.js does not exists"
  end
%>
<!-- if required locale does not exist, use the default "en" -->
<% if Rails.application.assets.find_asset "fullcalendar/dist/lang/#{Rails.application.secrets.fullcalendar_locale}.js" %>
  <script type="text/javascript" src="<%= asset_path "fullcalendar/dist/lang/#{Rails.application.secrets.fullcalendar_locale}.js" %>"></script>
<%
  elsif Rails.application.secrets.fullcalendar_locale != 'en'
    raise LoadError, "fullcalendar/dist/lang/#{Rails.application.secrets.fullcalendar_locale}.js does not exists"
  end
%>
</body>
</html>